M48
; DRILL file {KiCad 7.0.5} date Mon Apr 29 12:28:37 2024
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-04-29T12:28:37+10:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.5
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0256
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0669
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C0.1260
%
G90
G05
T1
X2.5112Y-1.3274
X2.7388Y-1.3274
T2
X1.3Y-1.5
X1.3Y-2.25
X1.7Y-1.5
X1.7Y-2.25
X2.05Y-1.5
X2.05Y-2.25
X2.45Y-1.5
X2.45Y-2.25
X2.8Y-1.5
X2.8Y-2.25
X3.2Y-1.5
X3.2Y-2.25
X3.55Y-1.5
X3.55Y-2.25
X3.95Y-1.5
X3.95Y-2.25
T3
X1.875Y-1.875
X3.375Y-1.875
T0
M30
